/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;

import br.com.infox.dal.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import javafx.scene.input.DataFormat;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author gabriel
 */
public class TelaPrincipal extends javax.swing.JFrame {
Connection conexao = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areatrabalho = new javax.swing.JDesktopPane();
        lblusu = new javax.swing.JLabel();
        lbldata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mencad = new javax.swing.JMenu();
        mencadcli = new javax.swing.JMenuItem();
        mencados = new javax.swing.JMenuItem();
        mencadusu = new javax.swing.JMenuItem();
        menre = new javax.swing.JMenu();
        menreser = new javax.swing.JMenuItem();
        menrecli = new javax.swing.JMenuItem();
        menaju = new javax.swing.JMenu();
        menajusob = new javax.swing.JMenuItem();
        menop = new javax.swing.JMenu();
        menopsair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setPreferredSize(new java.awt.Dimension(966, 486));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout areatrabalhoLayout = new javax.swing.GroupLayout(areatrabalho);
        areatrabalho.setLayout(areatrabalhoLayout);
        areatrabalhoLayout.setHorizontalGroup(
            areatrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        areatrabalhoLayout.setVerticalGroup(
            areatrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblusu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblusu.setText("Usuário");

        lbldata.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        lbldata.setText("Data");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/iconfinder_house-49_3947392 (2).png"))); // NOI18N

        mencad.setText("Cadastro");
        mencad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadActionPerformed(evt);
            }
        });

        mencadcli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mencadcli.setText("Cliente");
        mencadcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadcliActionPerformed(evt);
            }
        });
        mencad.add(mencadcli);

        mencados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mencados.setText("OS");
        mencados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadosActionPerformed(evt);
            }
        });
        mencad.add(mencados);

        mencadusu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mencadusu.setText("Usuários");
        mencadusu.setEnabled(false);
        mencadusu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mencadusuActionPerformed(evt);
            }
        });
        mencad.add(mencadusu);

        jMenuBar1.add(mencad);

        menre.setText("Relatório");
        menre.setEnabled(false);

        menreser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menreser.setText("Serviços");
        menreser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menreserActionPerformed(evt);
            }
        });
        menre.add(menreser);

        menrecli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_OPEN_BRACKET, java.awt.event.InputEvent.ALT_MASK));
        menrecli.setText("Clientes");
        menrecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menrecliActionPerformed(evt);
            }
        });
        menre.add(menrecli);

        jMenuBar1.add(menre);

        menaju.setText("Ajuda");

        menajusob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menajusob.setText("Sobre");
        menajusob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menajusobActionPerformed(evt);
            }
        });
        menaju.add(menajusob);

        jMenuBar1.add(menaju);

        menop.setText("Opções");

        menopsair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menopsair.setText("Sair");
        menopsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menopsairActionPerformed(evt);
            }
        });
        menop.add(menopsair);

        jMenuBar1.add(menop);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(areatrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusu)
                            .addComponent(lbldata))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblusu)
                .addGap(55, 55, 55)
                .addComponent(lbldata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addComponent(areatrabalho)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(982, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menrecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menrecliActionPerformed
        // TODO add your handling code here:
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório ?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo relatorio com o framework jasperreports
            try {
                // usando a classe jasperprint para preparar a impressao de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/reports/clientes.jasper",null,conexao);
                // a linha abaxo exibe o relatorio atravez da classe jasperviewer
                JasperViewer.viewReport(print,false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
                
        }
    }//GEN-LAST:event_menrecliActionPerformed

    private void menajusobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menajusobActionPerformed
        // TODO add your handling code here:
        TelaSobre sobre = new TelaSobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_menajusobActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // quando essa janela for ativada
         Date data = new Date();
         DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
         lbldata.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menopsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menopsairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair ?","Atenção",JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menopsairActionPerformed

    private void mencadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mencadActionPerformed

    private void mencadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadosActionPerformed
        // TODO add your handling code here:
        TelaOS OS = new TelaOS();
        OS.setVisible(true);
        areatrabalho.add(OS);
    }//GEN-LAST:event_mencadosActionPerformed

    private void mencadcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadcliActionPerformed
        // TODO add your handling code here:
                TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        areatrabalho.add(cliente);
    }//GEN-LAST:event_mencadcliActionPerformed

    private void mencadusuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mencadusuActionPerformed
        // TODO add your handling code here:
                TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        areatrabalho.add(usuario);
    }//GEN-LAST:event_mencadusuActionPerformed

    private void menreserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menreserActionPerformed
         //gerando um relatorio de serviços
        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório ?","Atenção",JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo relatorio com o framework jasperreports
            try {
                // usando a classe jasperprint para preparar a impressao de um relatorio
                JasperPrint print = JasperFillManager.fillReport("C:/reports/servicos.jasper",null,conexao);
                // a linha abaxo exibe o relatorio atravez da classe jasperviewer
                JasperViewer.viewReport(print,false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
                
        }
                                 
    }//GEN-LAST:event_menreserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areatrabalho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbldata;
    public static javax.swing.JLabel lblusu;
    private javax.swing.JMenu menaju;
    private javax.swing.JMenuItem menajusob;
    private javax.swing.JMenu mencad;
    private javax.swing.JMenuItem mencadcli;
    private javax.swing.JMenuItem mencados;
    public static javax.swing.JMenuItem mencadusu;
    private javax.swing.JMenu menop;
    private javax.swing.JMenuItem menopsair;
    public static javax.swing.JMenu menre;
    private javax.swing.JMenuItem menrecli;
    public static javax.swing.JMenuItem menreser;
    // End of variables declaration//GEN-END:variables
}
